[project]
name = "ifc-file-splitter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ifcopenshell>=0.8.4.post1",
    "typer>=0.21.1",
    "fastapi",
    "uvicorn",
    "python-multipart",
    "rich"
]
